# CS 345 Exercise 02:  NumPy

Solve the following exercises and submit the notebook via Canvas.

Everything you need for solving these exercises is contained in the [introduction to NumPy](https://github.com/asabenhur/CS345/blob/master/fall24/notebooks/module00_03_numpy.ipynb) notebook from the course github repository.

In [2]:
import numpy as np

### NaN and infinity

NumPy (and other computer languages/libraries) have a special value called `NaN` ([Not a Number](https://en.wikipedia.org/wiki/NaN)).
NaN is the result of various arithmetic operations, e.g. 0/0, $-\infty + \infty$.

In NumPy, NaN is represented as `np.nan`.  NaN satisfies the following properties:

* Comparisons of NaN with a number x using one of the operators =, <, >, >=, and <= is always False.  Consequently, x != NaN is always True.

* Any arithmetic operation involving a NaN leads to a NaN 

Infinity is represented using `np.inf`, and negative infinity is `-np.inf`.

* Experiment with NaN and infinity and convince yourself that the results of the following operations make sense to you:

```Pytnon
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - 1
```

In [3]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
np.nan - 1

nan
False
False


nan

### Creating arrays

* Create a 3x3 matrix with the integer values from 0 to 8.  We recommend doing this by creating a one dimensional array and converting it to a two dimensional array using the [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) function.  Please do not solve this by brute force!

In [7]:
matrix = range(9)
matrix = np.reshape(matrix, [3, 3])
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

* Create the same 3x3 matrix and have the end result be a floating point array with a dtype `float64`.

In [9]:
matrix = [float(val) for val in range(9)]
matrix = np.reshape(matrix, [3, 3])
matrix

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

* Create a vector (i.e. one dimensional array) of length 10 with random floating point values between 0 and 1.

In [12]:
vec = [np.random.rand() for v in range(10)]
vec

[0.5657867016136365,
 0.38147506003206755,
 0.22442045505412522,
 0.29951795881877685,
 0.2524670289721165,
 0.3298893131543479,
 0.573677141452945,
 0.2152757459567517,
 0.31657825986887667,
 0.9964246577847181]

* Create a 10x10 array with 1 on the border and 0 inside.

In [13]:
matrix = np.ones((10, 10))
matrix[1:-1, 1:-1] = 0
matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

* For an integer $n$, create an array of length $3n$ filled with the cyclic pattern 1, 2, 3.  For example, for $n=2$, the resulting array should be ```[1,2,3,1,2,3]```.  Hint:  slices!

In [19]:
n = 5
# replace with a correct implementation
pattern = np.array([1,2,3])
result = np.tile(pattern, n)
result

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### Slices

Describe the effect of each of the following slices of the following two-dimensional array, i.e. matrix:

```Python
a2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

Describe it in terms of rows and columns of the matrix.  As an example consider the following slice:

Slice 1:
```Python
a2d[0]
```

*answer:  the first row of the matrix*  

This is an example to illustrate what we are looking for.

Slice 2:
```Python
a2d[1, :2]
```

the first two values of the second row of the matrix

Slice 3:
```Python
a2d[:, -1]
```

the last column of the matrix

Slice 4:
```Python
a2d[:, 1:]
```

the last two columns of the matrix

Slice 5:
```Python
a2d[:,:]
```

the whole matrix

### Using NumPy Boolean arrays

* Replace all negative elements of the following array with the value 0.  This can be done with a single command! (Hint:  Boolean indexing).

In [24]:
a = np.array([-1, 3, -2, -3, 5, 6, -2])
# your code here
a[a < 0] = 0
a

array([0, 3, 0, 0, 5, 6, 0])

* Write a command that replaces all NaN values with 0 in the following array.  Use [np.isnan](https://numpy.org/doc/stable/reference/generated/numpy.isnan.html) with Boolean indexing.

In [25]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
# your code here
a[np.isnan(a)] = 0
a

array([1., 2., 3., 0., 5., 6., 7., 0.])

### Computing data statistics

* Given the two dimensional array below, write code to compute the mean value of each column and display the result.  *Do not use for loops!*  Instead, use the `axis` keyword of `np.mean`.

In [26]:
# computing column means of a 2d array.  You can use the following
# array as input.  Keep in mind that the result needs to be an array
# with 5 elements (same as the number of columns of the array)

a = np.array([[17.53, 18.55, 18.18, 10.8 , 10.08],
       [ 6.64, 15.78, 14.51, 12.4 , 14.6 ],
       [14.67,  2.02, 10.34,  3.79,  6.73],
       [12.61,  5.4 , 19.07, 13.76, 15.39],
       [ 1.82,  7.79,  5.41, 20.  , 18.17],
       [10.01,  8.88, 17.27,  1.73, 13.64]])

# your code below
np.mean(a, axis=0)

array([10.54666667,  9.73666667, 14.13      , 10.41333333, 13.10166667])

### A slicing challenge

Here's a more challenging exercise that you can solve using slices:

* Create a 8x8 matrix that looks like this:

```Python
[[0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]]
```

Hint:  even and odd numbered rows each are filled with the same pattern.


In [33]:
a = np.zeros((8,8))
a[::2, 1::2] = 1
a[1::2, ::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])